apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-kubernate-mysql-svc
  name: springboot-kubernate-mysql-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springboot-kubernate-mysql-app
  type: NodePort
status:
  loadBalancer: {}
